// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyfnaqvqytofesawninf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Zm5hcXZxeXRvZmVzYXduaW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjA1MDksImV4cCI6MjA3MDQzNjUwOX0.h71bnUty2--IXFZoSkirwkY6jsu8ssqw3GLQYOPzpes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});